deploy:
  provider: heroku
  language: node_js
  node_js:
    - 7
  api_key:
    secure: Q/tRkZOG9DVkCB0F5z0P8SBK/xHg/dS9tWzFFgoiELhjkZxsfjOfH3wlep8JC70aUoz1O3Ioz/rO8Yt5EZm5LwrrNTSaaznAfvBn/IfizJPN8/ABogTCYVIjARJr/LjJb3PJZhSFf+TMCt4CHbbm5YtTQ0eZGvFVk30xZd0M4bQFmvYT/rryQ570wIIbmDrEa33Ehe4PluwRjle4zK62haai0WfUJNH9vFh0vfOupmWBQPVMyjZZpUcT5qQXYbIVqQO/0Q/AL2348FC/mrtpRQF8RlH82RRfwdlgPZY9vI8xSBElsQgYlJTQajun8NhhFei1VDhNHHNxg1nvSz5OF2ip4Ex4o9K+BirSxE+3+8OgK+9jcAH4GddZem9MBVw6tcOYhwj1up3vAgL1remsv8PkOo7StK67/ahHslGN+EFjKLvS0jqDRG6sqnKGXu+IMy7LwKfkK5+0lrDntLcUmu+TrXQV82As7oGayLy6DVH6jlBqNOKTKA6QmHPV0f/Df7t60xjXyHwM8X+mfjo3o2U//rYLdzIh7Q6tind9ybSIWESqvu1SRcosEbSPISdlzcmJJNN3uqusWof4vA/yQu3BO9ltCLAtOzcfjG8Q9K/eOc/Rn16myyrKeBOIT0vpWlnkeYXBr9ORdTqflAHX7c6jLF8A5TGyOfrINJLw2VE=
  app: shag-test
